import "./fixtures/kitchen-sink-test.js"
import "./fixtures/lifecycle-test.js"
import "./fixtures/slot-test.js"
import "./fixtures/custom-accessor-test.js"
import "./fixtures/nested-element-test.js"
import "./fixtures/render-schedule-test.js"
